### PR TITLE
fix: remove a duplicate `R1CSShape` in the `RelaxedR1CSSNARK`'s chosen `ProverKey`

### LINKED ISSUE #65: Investigate R1CSShape inclusion in the Spartan ProverKey
See https://github.com/microsoft/Spartan2/pull/2/files
Is the same applicable to Nova, i.e. are we storing something that could be set up at proving time twice?

### PR DESCRIPTION
**Pull request by huitseeker**
As explained by @zaverucha in https://github.com/microsoft/Spartan2/pull/2 (with edits for precision):

The `R1CSShape` object was being stored in both:
- the `ProverKey` of the `spartan::direct::DirectSNARK`, which generically employs any instance of `RelaxedR1CSSNARKTrait`,
- the `ProverKey` of each of the two `RelaxedR1CSSNARKTrait` implementations in `spartan::{snark, ppsnark}::RelaxedR1CSSNARK`,
- the `PublicParams` that are passed to the proof method of `crate::CompressedSNARK<G1, G2, C1, C2, S1, S2>`, which generically employs any instance of `RelaxedR1CSSNARKTrait`.

IOW, `RelaxedR1CSSNARKTrait` is always accessed through generic structs (`DirectSNARK`, `CompressedSNARK`) which already have a copy of the relevant `R1CSShape`. We store it once in the top level object (`DirectSNARK`'s `ProverKey` or `PublicParams`) and pass it to the Spartan implementation.

This saves memory and makes serialization of the `ProverKey` about twice as fast. Both are significant when there are a large number of constraints.

Fixes #65 

```
group                                                        main                                   r1cs_shape_duplication
-----                                                        ----                                   ----------------------
CompressedSNARK-Commitments-StepCircuitSize-0/Prove          1.00       3.3±0.08s          1.00       3.3±0.06s
CompressedSNARK-Commitments-StepCircuitSize-0/Verify         1.01     45.6±0.62ms          1.00     45.3±0.49ms
CompressedSNARK-Commitments-StepCircuitSize-121253/Prove     1.00       8.1±0.06s          1.01       8.2±0.11s
CompressedSNARK-Commitments-StepCircuitSize-121253/Verify    1.00     62.5±1.17ms          1.02     63.6±2.98ms
CompressedSNARK-Commitments-StepCircuitSize-22949/Prove      1.00       5.4±0.13s          1.02       5.5±0.10s
CompressedSNARK-Commitments-StepCircuitSize-22949/Verify     1.01     51.2±0.65ms          1.00     50.8±0.34ms
CompressedSNARK-Commitments-StepCircuitSize-252325/Prove     1.00      15.7±0.05s          1.01      15.9±0.23s
CompressedSNARK-Commitments-StepCircuitSize-252325/Verify    1.00    110.4±0.43ms          1.06    117.0±0.64ms
CompressedSNARK-Commitments-StepCircuitSize-55717/Prove      1.00      10.1±0.04s          1.01      10.2±0.12s
CompressedSNARK-Commitments-StepCircuitSize-55717/Verify     1.16     72.0±0.91ms          1.00     62.0±0.81ms
CompressedSNARK-Commitments-StepCircuitSize-6565/Prove       1.00       5.9±0.11s          1.00       6.0±0.08s
CompressedSNARK-Commitments-StepCircuitSize-6565/Verify      1.03     52.3±2.47ms          1.00     50.8±0.54ms
CompressedSNARK-StepCircuitSize-0/Prove                      1.00    357.8±2.18ms          1.01    361.2±1.92ms
CompressedSNARK-StepCircuitSize-0/Verify                     1.00     20.8±0.11ms          1.00     20.9±0.29ms
CompressedSNARK-StepCircuitSize-1038757/Prove                1.00       9.9±0.01s          1.01      10.0±0.01s
CompressedSNARK-StepCircuitSize-1038757/Verify               1.00    131.3±1.08ms          1.02    133.5±0.84ms
CompressedSNARK-StepCircuitSize-121253/Prove                 1.00   1494.0±9.19ms          1.01   1503.4±8.83ms
CompressedSNARK-StepCircuitSize-121253/Verify                1.00     39.1±0.44ms          1.00     39.2±0.52ms
CompressedSNARK-StepCircuitSize-22949/Prove                  1.00    518.9±5.53ms          1.01    526.3±6.09ms
CompressedSNARK-StepCircuitSize-22949/Verify                 1.00     29.2±0.33ms          1.01     29.5±0.58ms
CompressedSNARK-StepCircuitSize-252325/Prove                 1.00       2.7±0.01s          1.01       2.7±0.01s
CompressedSNARK-StepCircuitSize-252325/Verify                1.00     50.6±0.68ms          1.01     51.3±0.67ms
CompressedSNARK-StepCircuitSize-514469/Prove                 1.00       5.1±0.01s          1.00       5.1±0.01s
CompressedSNARK-StepCircuitSize-514469/Verify                1.00     75.8±0.88ms          1.04     78.6±0.56ms
CompressedSNARK-StepCircuitSize-55717/Prove                  1.00   867.3±14.41ms          1.01   878.3±15.70ms
CompressedSNARK-StepCircuitSize-55717/Verify                 1.00     31.0±0.76ms          1.00     31.0±0.73ms
CompressedSNARK-StepCircuitSize-6565/Prove                   1.00    356.6±2.66ms          1.01    359.3±2.73ms
CompressedSNARK-StepCircuitSize-6565/Verify                  1.01     21.0±0.14ms          1.00     20.8±0.15ms
RecursiveSNARK-StepCircuitSize-0/Prove                       1.01     38.6±0.90ms          1.00     38.1±0.42ms
RecursiveSNARK-StepCircuitSize-0/Verify                      1.00     15.5±0.06ms          1.00     15.5±0.08ms
RecursiveSNARK-StepCircuitSize-1038757/Prove                 1.00    238.5±1.97ms          1.00    238.8±1.78ms
RecursiveSNARK-StepCircuitSize-1038757/Verify                1.01    170.1±1.52ms          1.00    168.0±1.81ms
RecursiveSNARK-StepCircuitSize-121253/Prove                  1.00     88.5±0.86ms          1.00     88.6±0.94ms
RecursiveSNARK-StepCircuitSize-121253/Verify                 1.00     53.8±0.94ms          1.00     53.7±1.34ms
RecursiveSNARK-StepCircuitSize-22949/Prove                   1.01     61.7±1.09ms          1.00     61.2±1.46ms
RecursiveSNARK-StepCircuitSize-22949/Verify                  1.00     32.8±0.08ms          1.00     32.7±0.19ms
RecursiveSNARK-StepCircuitSize-252325/Prove                  1.00    108.0±1.64ms          1.00    107.8±1.37ms
RecursiveSNARK-StepCircuitSize-252325/Verify                 1.00     68.5±0.46ms          1.00     68.7±0.39ms
RecursiveSNARK-StepCircuitSize-514469/Prove                  1.00    146.6±1.03ms          1.00    146.9±0.85ms
RecursiveSNARK-StepCircuitSize-514469/Verify                 1.01    100.1±0.48ms          1.00     99.5±0.20ms
RecursiveSNARK-StepCircuitSize-55717/Prove                   1.00     86.5±1.57ms          1.00     86.6±1.86ms
RecursiveSNARK-StepCircuitSize-55717/Verify                  1.00     56.7±0.22ms          1.00     56.8±0.30ms
RecursiveSNARK-StepCircuitSize-6565/Prove                    1.01     45.3±0.93ms          1.00     44.8±0.71ms
RecursiveSNARK-StepCircuitSize-6565/Verify                   1.00     20.7±0.08ms          1.00     20.7±0.24ms
```

### CODE REVIEW

**Comment by storojs72** [comment]
The organisation of traits in Rust software is always confusing. This is especially true for ZKP software. I believe that more similar optimisation can be found along our way of studying the Nova implementation and its design from different angles. In terms of further detecting such kind of optimisations specific to manipulation over Nova software design, probably it would be nice to invest some time in visualising traits organisation using some third-party tools for Rust (I guess they may exist). That may shed a bit of light on the design which is now clear only for early developers and reduce time for newcomers with pictorial way of thinking.

File: src/r1cs/mod.rs [hunk 1]
```diff
@@ -177,11 +177,12 @@ impl<G: Group> R1CSShape<G> {
   // Checks regularity conditions on the R1CSShape, required in Spartan-class SNARKs
   // Panics if num_cons, num_vars, or num_io are not powers of two, or if num_io > num_vars
   #[inline]
-  pub(crate) fn check_regular_shape(&self) {
-    assert_eq!(self.num_cons.next_power_of_two(), self.num_cons);
-    assert_eq!(self.num_vars.next_power_of_two(), self.num_vars);
-    assert_eq!(self.num_io.next_power_of_two(), self.num_io);
-    assert!(self.num_io < self.num_vars);
+  pub(crate) fn check_regular_shape(&self) -> bool {
```
Comment (porcuquine) [inline src/r1cs/mod.rs:180]: With this change, the documentation (which describes a panic) is out of date. The name is also misleading. Let's fix the documentation and change the name to one making clear this is a predicate, not an assertion.

**Review by porcuquine — APPROVED** [review]
Looks good, with a small modification noted.

**Review by porcuquine — APPROVED** [review]
