### PR TITLE
Simplify api

### LINKED ISSUE #63: `supernova::RecursiveSNARK::iter_base_step()` does not iterate `i`
The current setup for `RecursiveSNARK::iter_base_step()` does not iterate `RecursiveSNARK`'s internal step counter `i`. This leads to a [some strange logic](https://github.com/lurk-lab/arecibo/blob/c657b04a005182cb7bc1937f22b70dde747c1bdc/src/supernova/mod.rs#L554) for the first invocation of `prove_step()` that could potentially lead to some unexpected behavior/off-by-one errors.

I believe it should be possible to get rid of the above code snippet and retain logical consistency if `i` is iterated in the first step.

It may also be worth taking the time to rename `i` to something more clear like `num_steps`.

### PR DESCRIPTION
**Pull request by porcuquine**
Closes #63 & #64.

This PR simplifes the SuperNova API by:
- renaming `iter_base_step` to `new`
- minimize args to `supernova::RecursiveSnark::new` — almost matching those of `nova::RecursiveSnark::new`.
  - (The remaining extra arg is new — NonUniformCircuit, which helps derive removed args but cannot itself be eliminated.)
- minimize args to `supernova::RecursiveArgs::prove_step` — matching those of `nova::RecursiveSnark::prove_step`.

### CODE REVIEW

File: src/supernova/mod.rs [hunk 1]
```diff
@@ -577,10 +581,10 @@ where
   pub fn prove_step<C1: StepCircuit<G1::Scalar>, C2: StepCircuit<G2::Scalar>>(
     &mut self,
     pp: &PublicParams<G1, G2, C1, C2>,
-    circuit_index: usize,
     c_primary: &C1,
     c_secondary: &C2,
   ) -> Result<(), SuperNovaError> {
+    let circuit_index = c_primary.circuit_index();
```
Comment (adr1anh) [inline src/supernova/mod.rs:587]: Consider adding a check to ensure this matches `self.program_counter`.

**Review by adr1anh — COMMENTED** [review]
Does it still make sense for `RecursiveSNARK` to expose `[get_program_counter](https://github.com/lurk-lab/arecibo/blob/8e7509459f2dd51c83f9199186c8db30d5bf2a6d/src/supernova/mod.rs#L926)`

File: src/supernova/mod.rs [hunk 2]
```diff
@@ -938,9 +942,14 @@ where
...
-  /// Initial program counter, defaults to zero.
+  /// Initial program counter is the initial circuit index as a `Scalar`.
   fn initial_program_counter(&self) -> G1::Scalar {
-    G1::Scalar::ZERO
+    G1::Scalar::from(self.initial_circuit_index() as u64)
+  }
+
+  /// Initial circuit index, defaults to zero.
+  fn initial_circuit_index(&self) -> usize {
+    0
```
Comment (huitseeker) [inline src/supernova/mod.rs:952]: This API allows de-synchronizing the `usize` and `Scalar` representations of the initial program counter. It would be better to add `initial_program_counter` as an extension trait (a trait with a blanket implementation for `T: NonUniformCircuit`), then Rust will guarantee *that* implementation is the only one that can apply.

File: src/supernova/mod.rs (hunk 1 above)
Comment (porcuquine) [reply src/supernova/mod.rs]: Done.

File: src/supernova/mod.rs (hunk 2 above)
Comment (porcuquine) [reply src/supernova/mod.rs]: Done.

**Review by huitseeker — APPROVED** [review]
Makes sense to me!

**Review by mpenciak — APPROVED** [review]
